### ISSUE TITLE
website using this data ?

### ISSUE THREAD

**Issue by Foul-Tarnished** [EldenRingDatabase/erdb#11]
Everybody hates Fextralife, and WikiDot is just outdated and manually done.

We really need a website with a clean UI that use this data

I replicated Fextralife html/css UI for weapons
but loading JSON with javascript is a mess (well, webdev is a mess)
too lazy to use 200 other softwares like node.js, because it doesn't want to load local files...

**Comment by Phil25** [comment]
There are some projects of mine that use these data but I haven't had much time to work on them recently. Namely:

- a wiki page (armaments only): https://erdb.wiki/items/armaments/
- AR calculator: https://erdb.wiki/tools/ar-calculator

Both are generated straight from the game and are a heavy work in progress. Their repository is [here](https://github.com/EldenRingDatabase/eldenringdatabase.github.io).

Other than those I know https://er-build-planner.nyasu.business/ is also using ERDB.

**Comment by Foul-Tarnished** [comment]
Did you try to do the static wikipedia I talked about above ?

If I try to use it in a folder where I only have the json downloaded from the rest API (so not from a manually generated ERDB) I get this :

```
PS C:\Users\ngermann01\Documents\ER-database\json> erdb generate-wiki --data-path . --out ../wiki-test
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\ngermann01\AppData\Local\Programs\Python\Python311\Scripts\erdb.exe\__main__.py", line 4, in <module>
  File "C:\Users\ngermann01\AppData\Local\Programs\Python\Python311\Lib\site-packages\erdb\main\cli.py", line 4, in <module>
    from erdb.main.app import App
  File "C:\Users\ngermann01\AppData\Local\Programs\Python\Python311\Lib\site-packages\erdb\main\app.py", line 5, in <module>
    from erdb.main.args import parse_args
  File "C:\Users\ngermann01\AppData\Local\Programs\Python\Python311\Lib\site-packages\erdb\main\args.py", line 7, in <module>
    from erdb.table import Table
  File "C:\Users\ngermann01\AppData\Local\Programs\Python\Python311\Lib\site-packages\erdb\table\__init__.py", line 6, in <module>
    from erdb.table.ammo import AmmoTableSpec
  File "C:\Users\ngermann01\AppData\Local\Programs\Python\Python311\Lib\site-packages\erdb\table\ammo.py", line 1, in <module>
    from erdb.typing.models.ammo import Ammo
  File "C:\Users\ngermann01\AppData\Local\Programs\Python\Python311\Lib\site-packages\erdb\typing\models\__init__.py", line 3, in <module>
    from pydantic import ConfigDict, Extra, ConstrainedStr
  File "C:\Users\ngermann01\AppData\Local\Programs\Python\Python311\Lib\site-packages\pydantic\__init__.py", line 210, in __getattr__
    return _getattr_migration(attr_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ngermann01\AppData\Local\Programs\Python\Python311\Lib\site-packages\pydantic\_migration.py", line 295, in wrapper
    raise PydanticImportError(f'`{import_path}` has been removed in V2.')
pydantic.errors.PydanticImportError: `pydantic:ConstrainedStr` has been removed in V2.

For further information visit https://errors.pydantic.dev/2.1.1/u/import-error
```

**Comment by Foul-Tarnished** [comment]
https://erdb.wiki/items/armaments/ looks really clean

I hope it will get updated with all other stuff like ammo, armor, etc

**Comment by Phil25** [comment]
> Did you try to do the static wikipedia I talked about above ?

Yes, the wiki page and AR calculator are both generated using `generate-wiki` and hosted on GitHub Pages.

> Not sure if it's because I don't have a true generated ERDB, or if it's this code or the pip package that is outdated in some way

I'm not sure what this error means exactly but it appears ERDB is using an outdated verson of Pydantic. Like I said, I haven't worked on this project on a while so it might be the case. I'll leave this issue open to take a look in the meantime.

**Comment by Foul-Tarnished** [comment]
If a small donation can make you work on this sooner, I would gladly do it
Well nothing that would be a fair salary for a developper, just something like 20$

**Comment by Phil25** [comment]
Thanks for the kind words and the donation offer, very much appreciated 😁

But honestly, this project gaining traction works better for me than a donation, so I’m gonna try to fit it in my spare time eventually. I just have a bit on my plate at the moment.

For now, I will update it to 1.10 and take it off from then when I’ll find some time.

Thanks again!

**Comment by flosrn** [comment]
I'm currently planning to build a website using this data but I'm developer, not designer, so if you have useful ressources or inspirations I will be happy if you could post there here. 

The idea is to build a website with great and clean UI, everybody know Fextralife is awful

**Comment by joeyfigaro** [comment]
@flosrn if you're not a dev or designer, in my opinion the most valuable thing you could do would be to create a centralized repository (not a spreadsheet) of all game data in JSON. CSV would be okay too, but JSON is preferable. 

People have started repositories, but it looks like they've all been abandoned. There's a public REST api you could use to store all response data: https://docs.eldenring.fanapis.com/docs/

**Comment by flosrn** [comment]
@joeyfigaro yes I already saw this API but I based my website on this one: https://github.com/EldenRingDatabase/erdb

If you want you can check my website (wip) here: https://elden-archives.vercel.app

**Comment by EthanShoeDev** [comment]
Another website using this data: https://www.eldenringcompass.com

Automatically reads the save file to give more data.

**Comment by Phil25** [comment]
Hey guys, sorry for posting so little updates on this.

It’s difficult for me to say when the new data will come as I would have to fix ERExporter first, and upon initial inspection it wasn’t as straightforward. Mostly it’s some C# env issues since I’m not very versed in the language. After that, erdb will have to be updated with new item types.

The truth is, I have very little time to work on this project nowadays, but I’m really hoping to sit down to update it at the very least.

**Comment by FiletMignom** [comment]
I'm beginning development on a project that's supposed the ideal Elden Ring database for both old and new players. I'm designing the interface from scratch using the game's UI design as reference. I'm using https://api.erdb.wiki/v1/docs#/ as my main source of data but there's tons of things missing such as skills and enemies. It's a big project so any help would be greatly appreciated. If you're interested feel free to reach out and I'll link you my discord where I'm currently sharing my progress.

**Comment by FiletMignom** [comment]
Well peeps, it appears I'm a moron cuz I can't figure out how to contact people through gitHub, so I made a discord: https://discord.gg/5REvrb3K.
Here's the thing, I'm doing it, a non-bullshit Elden Ring database with crisp UI and decent user experience using https://api.erdb.wiki/v1/docs#/ as my main source of content. But before I publish anything, I want to reach my first goal of this project, which is having a 'main-armaments' page containing all the info and a list of every ashes-of-war compatible with each and every weapon in the game.
The reason why I'm reaching out here is because I'm not so experienced outside of web-development, and because erdb is missing things such as skills I'm afraid I'll have to extract some game files myself. If you think you can help me on this matter feel free joining the discord so we can talk about it, for now, have this preview of the main armaments page made with javascript+css.
![image](https://github.com/user-attachments/assets/1b0db04f-a060-4964-a230-2dd6484dd3d3)
